### PR TITLE
Update lookup-window.js to work with mocha

### PR DESCRIPTION
**Pull request by jsmestad**
## Why

The ember-cli-mocha acceptance test blueprint does not work with lookup-window.

```js
import { describe, it, beforeEach, afterEach } from 'mocha';
import { expect } from 'chai';
import startApp from 'my-app/tests/helpers/start-app';
import destroyApp from 'my-app/tests/helpers/destroy-app';

import { lookupWindow } from 'ember-window-mock';


describe('Acceptance | homebot email authentication', function() {
  let application;

  beforeEach(function() {
    application = startApp();
  });

  afterEach(function() {
    destroyApp(application);
  });

  it('redirects to our the login service', function() {
    let window = lookupWindow(application);
    visit('/auth/success');

    return andThen(() => {
      expect(window.location.href).to.equal('http://localhost/login');
    });
  });
});
```

## Changes

Allow `lookupWindow` to accept the application itself.

### CODE REVIEW

**Comment by simonihmig** [comment]
@jsmestad Thanks for your efforts here! I am just not sure we really need this. We also use mocha in our companies apps, and it works there without any problem. 

As you can see [here](https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/tests/helpers/module-for-acceptance.js#L9) the default `module-for-acceptance` helper sets the application on the `this` context, so the `lookupWindow` helper should actually find the container even without your changes! That is when you pass `this`, like in `let window = lookupWindow(this);`

**Comment by jsmestad** [comment]
@simonihmig yeah we are new to ember-mocha, i can hopefully dig into why a bit this weekend. Appreciate the help!

**Comment by simonihmig** [comment]
@jsmestad no problem. Have a look at your `tests/helpers/module-for-acceptance.js` if it matches the default one I linked above, which should set `this.application`. Also you can set a breakpoint somewhere in your tests and then inspect `this` to see if it has the application set. If that's the case, the `lookupWindow` helper *should* work as it is!

**Comment by simonihmig** [comment]
Closing this as #41 will remove `lookupWindow`.

**Pull request closed without merging**
