### PR TITLE
Move window-mock and test helpers to addon-tree-support

### LINKED ISSUE #1: [Feature request] Exclude window-mock from production build

### PR DESCRIPTION
**Pull request by simonihmig**
Fixes #1

### CODE REVIEW

**Comment by simonihmig** [comment]
@turbo87 as per your suggestion, I moved the test related stuff to `addon-test-support`. Mind having a look if that makes sense what I did here?

It was a bit tricky, because previously the initializer would import the `window-mock` service. But when that is moved to `addon-test-support`, this module would not be defined when not in test mode, so the loader would throw. So I applied this (shamelessly stolen) trickery here, to allow the modules in `addon-test-support` to override those in `addon`: https://github.com/kaliber5/ember-window-mock/pull/2/files#diff-168726dbe96b3ce427e7fedce31bb0bc.

This makes it possible to have a [simplified initializer](https://github.com/kaliber5/ember-window-mock/pull/2/files#diff-586db04332f0e8f607458b4125384899) for normal usage (dev or production), that does not import `window-mock`, and an [test-mode initializer](https://github.com/kaliber5/ember-window-mock/pull/2/files#diff-db5e25a0345a23eb8a90a76e3e4857cf) (in `test-support.js`) with the same module name, so it will override the default initializer when testing (`test-support.js` is included). Does that make sense?

**Comment by Turbo87** [comment]
I'm wondering if you need the initializer at all now? Can't you just rename the server to `window` and remove the initializer?

Also I think the stuff from `addon-test-support` is only loaded during testing so I'm not sure why you have the `isTesting` check in the test initializer? If you can remove that you will probably be able to remove the whole test initializer too.

**Comment by simonihmig** [comment]
> I'm wondering if you need the initializer at all now? Can't you just rename the server to window and remove the initializer?

Hm, yes, I think you're right. With the way the module itself is overwritten now, I think that makes sense. Thanks for feedback, will try this out! 👍

**Comment by simonihmig** [comment]
> I'm wondering if you need the initializer at all now? Can't you just rename the server to window and remove the initializer?

I was a bit too with my previous judgement. I still need the initializer because of `{ instantiate: false }`, which is needed because `window` is not an `Ember.Service`.

I renamed both the services to have the same name, so at least the mock will automatically override the default module. Therefore the test initializer is not needed anymore.

Btw, seems somehow the `register` options (`{ instantiate: false }`) are not taken into account when the service can be automatically looked up by its name. Got `Assertion Failed: Expected service:window to resolve to an Ember.Service but instead it was [object Window]`. So moved away from `/app/services/window`, which seems to work now. Don't know if that's a bug or a feature... 🤔

**Comment by Turbo87** [comment]
nice work. sounds like reasonable changes :)

**Comment by simonihmig** [comment]
Released as 0.1.0

**Pull request merged**
