### PR TITLE
add failing test for function bind

### PR DESCRIPTION
**Pull request by kellyselden**
Failing test for #26.

### CODE REVIEW

**Comment by simonihmig** [comment]
@kellyselden Thanks! 👍

**Comment by simonihmig** [comment]
Hm, actually tests seem to be failing for some other reason. `this.sinon` is undefined. Should be `this.spy()` probably: https://travis-ci.org/kaliber5/ember-window-mock/jobs/309760712#L626

**Comment by kellyselden** [comment]
My bad. Fixed.

**Comment by simonihmig** [comment]
Closed in favor of #28, which should hopefully fix this. Thanks again!

**Pull request closed without merging**
